### ISSUE TITLE
[Proposal] openpai-runtime interface

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/openpai-runtime#12]
Currently, opnepai-runtime is tightly coupled with PAI and Framework Controller. We need decouple with these components for independent release cycle and efficient development.

## Methods:
Treat all PAI related logical as `runtime-plugin`. Then `openpai-runtime` only keep main logical, PAI related code will maintained in PAI repo.
To implement this, we need `init-plugin` and `runtime-plugin`.  

### Init plugin config spec
For `init-plugin`, it will run in init container, a spec for `init-plugin`. The plugins will run sequentially :
```yaml
initPlugins:
  - name: frameworkParser
    command: pai/frameworkBarrier
    args:
      - framework.json
  - name: pai/frameworkParser
    command: pai/frameworkParser.py
    args:
      - pai/framework.json
    errors:
      - name: FrameworkBarrierTimeout
        originErrorCode: 201
        mappedErrorCode: 251
  - name: imageChecker
    command: imageChecker.py
  - name: portChecker
    command: portChecker.py
    args:
      - portChecker.py
      - portListFile
```

### Pass init plugin config to runtime
This spec can be transfer to runtime through `INIT_PLUGINS` env or can be a file named `init_plugins.yaml` under `PAI_CONFIG_DIR`. We will try to parse  `INIT_PLUGINS` env first. If this env is empty, we will try to read `init_plugins.yaml`. If `init_plugins.yaml` is absent, the default config  `init_plugins_default.yaml`  will be used.

### Result
After this change runtime will only keep common plugin in init container:
`imageChecker`, `userCommandRender`, `portConflictChecker`, `envGenerator`. Each plugin will have clear interface and developer can reuse these plugins (just like linux command).
PAI related plugins will move to PAI repo. such as `frameworkBarrier`, `frameworkParser`...

### Other interface
Runtime spec need to be passed through `RUNTIME_SPEC` env

The spec for runtime is using PAI protocol
```yaml
protocolVersion: 2
name: test_e7a7fe4e
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'openpai/standard:python_3.6-pytorch_1.2.0-gpu'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    dockerImage: docker_image_0
    commands:
      - sleep 10
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
    - plugin: teamwise_storage
      parameters:
        storageConfigNames:
          - confignfs
```
secret file should stored at `${PAI_CONFIG_DIR}/secret.yaml` and exit-spec should stored at `${PAI_CONFIG_DIR}/runtime-exit-spec.yaml`

**Pro**:
For new runtime requirement, can be implement rather as init_plugin and runtme_plugin. Do not need to change runtime code is the feature is PAI specific.
Runtime can be reused by other project 

**Con**:
New interface, much work to do. Complex data/config pass through env, not friendly for end-user.
